### ISSUE TITLE
Set datatype does not understand non-string values

### ISSUE THREAD

**Issue by aprilrd** [facetjs/facetjs#16]
```
expect(
  Set.fromJS({values: [1, 2]}).toJS()
).to.deep.equal({values: [1, 2]})
```
currently fails

**Comment by vogievetsky** [comment]
Hehe, funny. Working on that right now in a branch called `refcheck` https://github.com/facetjs/facetjs/tree/refcheck

Actually already fixed that particular problem, check out the unit tests: https://github.com/facetjs/facetjs/blob/refcheck/test/core/datatypes/set.mocha.coffee

That some other unit tests need to be fixed and than the branch can be merged.

**Comment by aprilrd** [comment]
Cool! Once that's fixed we have a passing travis!
