### ISSUE TITLE
RemoteDataset should default to throwing errors instead of returning true

### ISSUE THREAD

**Issue by aprilrd** [facetjs/facetjs#24]
RemoteDataset does not have any database backing and, thus, cannot handle any kind of queries. So it makes logical sense for RemoteDataset's `handle***` methods to throw errors. That change will also make developing a new RemoteDataset a bit easier.

Example)
https://github.com/facetjs/facetjs/blob/remote_dataset_logic/src/core/datatypes/remoteDataset.ts#L159

**Comment by aprilrd** [comment]
This issue concerns a working branch: `remote_dataset_logic`.

**Comment by vogievetsky** [comment]
Thanks, I have addressed this in the code. https://github.com/facetjs/facetjs/pull/25
